package com.aleksandarparipovic.marel_app.bonus_min_hours_rules;

import com.aleksandarparipovic.marel_app.user.User;
import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.Generated;
import org.hibernate.generator.EventType;
import org.hibernate.annotations.UpdateTimestamp;

import java.time.LocalDate;
import java.time.OffsetDateTime;

@Entity
@Table(name = "bonus_min_hours_rules")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class BonusMinHoursRule {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(name = "period", nullable = false)
    private LocalDate period;

    /**
     * What the WORK CALENDAR says the month's minimum is.
     *
     * <p>Kept up to date by {@code BonusCalendarSyncService} on every calendar edit, and
     * never the number to apply on its own — see {@link #effectiveMinNumHours}.
     */
    @Column(name = "min_num_hours", nullable = false)
    private Integer minNumHours;

    /**
     * What a person set by hand, or null when nobody has.
     *
     * <p>Survives calendar edits on purpose: the calendar keeps maintaining its own answer in
     * {@link #minNumHours} underneath, so resetting this to null returns the month to the
     * CURRENT calendar value rather than the one that stood when the override was made.
     */
    @Column(name = "manual_min_num_hours")
    private Integer manualMinNumHours;

    @Column(name = "manual_set_at")
    private OffsetDateTime manualSetAt;

    @Column(name = "manual_set_by")
    private Long manualSetBy;

    /**
     * The same column again, read-only, so the screen can say WHO rather than an id.
     *
     * <p>Two mappings of one column: the {@code Long} above is what the service writes, and
     * this one is only ever read. Same idiom as {@code OperationNormVersion.createdBy}.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "manual_set_by", insertable = false, updatable = false)
    private User manualSetByUser;

    /**
     * The number to apply — the manual one when there is one, the calendar's otherwise.
     *
     * <p>Generated by the database (COALESCE), so no reader can accidentally apply the
     * calendar's value to a month somebody has deliberately overridden.
     *
     * <p>Never written from here, and read back after INSERT <em>and</em> UPDATE. The update
     * half is not optional: {@code @Generated} refreshes only on insert by default, so
     * without it the value returned straight after setting or clearing an override would be
     * the one it just replaced.
     */
    @Generated(event = {EventType.INSERT, EventType.UPDATE})
    @Column(name = "effective_min_num_hours", insertable = false, updatable = false)
    private Integer effectiveMinNumHours;

    @CreationTimestamp
    @Column(name = "created_at", nullable = false, updatable = false)
    private OffsetDateTime createdAt;

    @UpdateTimestamp
    @Column(name = "updated_at")
    private OffsetDateTime updatedAt;

    @Column(name = "archived_at")
    private OffsetDateTime archivedAt;
}

