package com.aleksandarparipovic.marel_app.employment_period;

import com.aleksandarparipovic.marel_app.employee.Employee;
import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.Generated;
import org.hibernate.generator.EventType;

import java.time.LocalDate;
import java.time.OffsetDateTime;

/**
 * One spell of employment.
 *
 * <p><b>The authority for when somebody worked here.</b>
 * {@code employees.employment_start_date}, {@code employment_end_date} and
 * {@code probation_end_date} mirror the LATEST period and are maintained by
 * {@code trg_eep_sync_employee} — a database trigger rather than application
 * code, so no write path can forget them.
 *
 * <p>An employee can leave and return, which is the whole reason this exists: as
 * two columns on the employee row a rehire either erased the first spell or
 * needed a second employee record, splitting one person's work, payroll and audit
 * trail in two.
 */
@Entity
@Table(name = "employee_employment_periods")
@Getter @Setter @NoArgsConstructor @AllArgsConstructor @Builder
public class EmployeeEmploymentPeriod {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "employee_id", nullable = false)
    private Employee employee;

    @Column(name = "started_on", nullable = false)
    private LocalDate startedOn;

    /** Inclusive. NULL while the employee is still here. */
    @Column(name = "ended_on")
    private LocalDate endedOn;

    /**
     * Probation length for THIS spell, in days.
     *
     * <p>Zero by default: a returning employee serves no new probation unless an
     * administrator says so. The FIRST period is opened with the employee's own
     * {@code norm_grace_days} instead — see {@code EmploymentPeriodService}.
     */
    @Column(name = "norm_grace_days", nullable = false)
    @Builder.Default
    private Integer normGraceDays = 0;

    /**
     * {@code started_on + norm_grace_days}, generated by the database.
     *
     * <p>Generated because it is arithmetic over two columns of this same row, so
     * it cannot drift from them and can be queried. On {@code employees} the same
     * name is a plain trigger-maintained column, because there its value comes
     * from another table and a generated column cannot be written.
     */
    // @Generated so Hibernate SELECTs it back after every write. Without it, code
    // that changes started_on or norm_grace_days and then asks ProbationPolicy in
    // the SAME transaction reads the value from before the change — and the answer
    // decides whether somebody is paid a weekend bonus.
    @Generated(event = {EventType.INSERT, EventType.UPDATE})
    @Column(name = "probation_end_date", insertable = false, updatable = false)
    private LocalDate probationEndDate;

    @Column(name = "note", columnDefinition = "TEXT")
    private String note;

    @Column(name = "created_at", nullable = false, updatable = false, insertable = false)
    private OffsetDateTime createdAt;

    @Column(name = "updated_at", insertable = false)
    private OffsetDateTime updatedAt;

    @Column(name = "archived_at")
    private OffsetDateTime archivedAt;
}
