spring.application.name=marel-app

server.port=8080

# ===============================
# DATABASE
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/marel_app
spring.datasource.username=aleksandarparipovic
spring.datasource.password=Stic020919!

# ===============================
# JPA / HIBERNATE (DEV ONLY)
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=validate

# ===============================
# BOOTSTRAP ADMIN (DEV ONLY)
# ===============================
app.bootstrap.admin.password=Admin123!

# ===============================
# SECURITY TOKENS
# ===============================
app.security.jwt.secret=super-secret-key-change-later-super-secret
app.security.jwt.access-token-ttl-seconds=900
app.security.refresh-token.ttl-seconds=2592000
app.security.refresh-token.cookie-name=refresh_token
app.security.refresh-token.cookie-secure=false
app.security.refresh-token.cookie-same-site=Lax
app.security.cors.allowed-origins=http://localhost:5123,http://localhost:5173,http://localhost:3000
