-- =============================================================================
-- Every scheme x category pair gets an explicit rule  (D6)
-- =============================================================================
-- Until now a missing rule meant ALLOW. That default was chosen for a good reason
-- — a payslip line that silently disappears is far harder to notice than an extra
-- one — but it makes the configuration unreadable: 21 of 26 pairs had no row on
-- 2026-07-31, so most of what the system does was not written down anywhere.
--
-- D6 replaces both defaults with a third answer: a MISSING rule is an incomplete
-- configuration, and an incomplete configuration is an error. That is only usable
-- if the matrix is complete first, which is what this migration does.
--
-- NOTHING CHANGES BEHAVIOUR HERE. The generated rows reproduce exactly what the
-- ALLOW default produced: is_allowed = true, everything else inheriting from the
-- category. The explicit denies that already exist are left untouched.
--
-- Re-runnable. Ends by raising if any pair is still missing, so a half-applied
-- matrix cannot pass for a complete one.
-- =============================================================================

-- ── Foreign: meal and transport are excluded AND invisible ──────────────────
-- The deny rows already exist from 2026-07-27-10. What they lacked is the
-- visibility half: a denied line got no adjustment row, so it vanished from the
-- payslip as a side effect rather than because anyone said it should. Saying it
-- explicitly is what lets the frontend stop guessing.
UPDATE payroll_adjustment_category_scheme_rules r
SET visible_in_ui  = FALSE,
    visible_in_pdf = FALSE
FROM compensation_schemes s, payroll_adjustment_categories c
WHERE r.compensation_scheme_id = s.id
  AND r.payroll_adjustment_category_id = c.id
  AND s.code = 'FOREIGN_FIXED_COEFFICIENT'
  AND c.code IN ('MEAL_ALLOWANCE', 'TRANSPORT_ALLOWANCE')
  AND r.is_allowed = FALSE
  AND r.archived_at IS NULL
  AND r.visible_in_ui IS NULL;


-- ── Fill in every remaining pair, reproducing today's behaviour ─────────────
INSERT INTO payroll_adjustment_category_scheme_rules
    (compensation_scheme_id, payroll_adjustment_category_id,
     is_allowed, calculation_mode, valid_from, note)
SELECT s.id,
       c.id,
       TRUE,
       'INHERIT',
       DATE '2020-01-01',
       'Generated by 2026-08-15-03. Reproduces the ALLOW default that applied before'
       || ' a missing rule became an error (D6). Behaviour unchanged.'
FROM compensation_schemes s
CROSS JOIN payroll_adjustment_categories c
WHERE s.archived_at IS NULL AND s.is_active
  AND c.archived_at IS NULL AND c.is_active
  AND NOT EXISTS (
      SELECT 1
      FROM payroll_adjustment_category_scheme_rules r
      WHERE r.compensation_scheme_id = s.id
        AND r.payroll_adjustment_category_id = c.id
        AND r.archived_at IS NULL
        AND r.is_active);


-- ── The matrix must now be complete ────────────────────────────────────────
DO $$
DECLARE
    v_missing INTEGER;
    v_pairs   INTEGER;
    v_denies  INTEGER;
BEGIN
    SELECT count(*) INTO v_missing
    FROM compensation_schemes s
    CROSS JOIN payroll_adjustment_categories c
    WHERE s.archived_at IS NULL AND s.is_active
      AND c.archived_at IS NULL AND c.is_active
      AND NOT EXISTS (
          SELECT 1 FROM payroll_adjustment_category_scheme_rules r
          WHERE r.compensation_scheme_id = s.id
            AND r.payroll_adjustment_category_id = c.id
            AND r.archived_at IS NULL
            AND r.is_active);

    IF v_missing > 0 THEN
        RAISE EXCEPTION 'Configuration matrix still incomplete: % scheme x category pair(s) '
            'have no rule. The calculation refuses to guess, so this must not ship '
            'half-applied.', v_missing;
    END IF;

    SELECT count(*) INTO v_pairs
    FROM compensation_schemes s CROSS JOIN payroll_adjustment_categories c
    WHERE s.archived_at IS NULL AND s.is_active
      AND c.archived_at IS NULL AND c.is_active;

    SELECT count(*) INTO v_denies
    FROM payroll_adjustment_category_scheme_rules
    WHERE archived_at IS NULL AND is_active AND is_allowed = FALSE;

    RAISE NOTICE 'Configuration matrix complete: % pair(s), % of them explicit denies.',
        v_pairs, v_denies;
END $$;
