BEGIN;

ALTER TABLE monthly_reports
    DROP CONSTRAINT IF EXISTS uq_monthly_reports_employee_period;

DROP INDEX IF EXISTS idx_monthly_reports_employee_period;

ALTER TABLE monthly_reports
    ADD CONSTRAINT uq_monthly_reports_employee_record_period
        UNIQUE (employee_record_id, start_date, end_date);

-- Default FK name generated by Postgres for employee_id references.
ALTER TABLE monthly_reports
    DROP CONSTRAINT IF EXISTS monthly_reports_employee_id_fkey;

ALTER TABLE monthly_reports
    DROP COLUMN IF EXISTS employee_id;

COMMIT;

