-- =============================================================================
-- Step 3 — does the line say the same thing as the column it will replace?
-- =============================================================================
-- SPENT. Every column this compared has been dropped, so the queries that used
-- to run here would now fail on a missing column rather than report anything.
-- The file is kept for what it concluded and for the two mistakes it took to
-- get there — both of which apply to the next dual-write, whenever that is.
--
-- WHAT IT WAS FOR
-- Step 2 made the LINE the source: the recalculation decided from
-- payroll_adjustments and wrote the payroll_run_items columns from it. While
-- both were written the two had to agree on every item, because where they did
-- not, one of them was wrong and the difference was somebody's pay.
--
-- WHAT IT CONCLUDED
--   * 2472 lines across 849 items, every one through the component calculator
--   * 0 real drift for meal, transport and the bonus
--   * three employees on three configurations were then edited THROUGH THE
--     SCREEN and re-verified, because a sweep proves the read path and only
--     real editing proves the write path
-- On that evidence the columns went: meal and transport in
-- 2026-09-04-01-drop-meal-and-transport-mirror-columns.sql, the nine bonus
-- columns in 2026-09-06-01-drop-bonus-mirror-columns.sql. payroll_run_items went
-- from 66 columns to 44.
--
-- THE TWO MISTAKES, because they are the reusable part
--
-- 1. DRIFT WAS SPLIT ON THE WRONG FLAG. A line that has never been through the
--    component calculator will differ, and that is not a fault — it is work not
--    yet done. The test for it is payroll_adjustments.calculated_at IS NULL, NOT
--    payroll_run_items.needs_recalculation: an item calculated a year ago under
--    the old code is not marked stale either, so that flag counts the wrong
--    thing. Getting this wrong reported six items as real drift when every one
--    of them had calculated_at NULL.
--
-- 2. count(*) OVER A LEFT JOIN COUNTS THE NULL ROW. A family with nothing wrong
--    reported exactly 1 forever, and it looked like one stubborn item that no
--    amount of recalculation would clear. count(d.id) is the fix. A diagnostic
--    that cannot reach zero is worse than no diagnostic: it teaches you to
--    ignore it.
--
-- WHAT IS STILL LIVE
-- docs/business-rules/payroll-verify-one-employee.sql — run it after editing one
-- employee's month through the screen. That one still works, because it reads
-- the line rather than comparing it to anything.
-- =============================================================================

\echo 'payroll-step3-column-vs-line.sql is spent: the columns it compared are gone.'
\echo 'Read the header for what it found. For a live check, use:'
\echo '  psql -d marel_app -v emp=17 -v period="''2026-08-01''" \'
\echo '       -f docs/business-rules/payroll-verify-one-employee.sql'
