-- =============================================================================
-- A person looks after their own account
-- =============================================================================
-- WHAT CHANGES
--   1. users.display_name — an optional name to be shown by, apart from the
--      legal first/last name the payroll and the registers use.
--
--   2. email_change_requests — a pending change of sign-in address, held until
--      the person proves they can read the NEW mailbox.
--
-- WHY (2) IS A TABLE AND NOT A COLUMN
--   The address only changes at the END of the exchange. Until the code from the
--   new mailbox comes back, the OLD address is still the one that signs in and
--   still the one notifications reach — so the new address cannot sit in
--   users.email_address, and a "pending_email" column beside it would be a second
--   half-state on the row everything else reads.
--
--   Holding it apart also gives the attempt counter somewhere to live. A six-digit
--   code is guessable in a million tries; the counter is what makes that one
--   attempt at a time instead of a million.
--
--   THE CODE IS STORED HASHED, never in the clear. A stolen backup of this table
--   must not hand anybody a live code, exactly as it must not hand them a
--   password.
--
-- MIGRATION IMPACT
--   · users gains one nullable column. No existing row changes, no query breaks.
--   · The new table starts empty and is read by nothing until somebody starts a
--     change.
--   · Rollback: DROP TABLE email_change_requests; ALTER TABLE users DROP COLUMN
--     display_name.
--   · Every step is guarded, so replaying the migration is safe.
-- =============================================================================

-- ── 1. A name to be shown by ────────────────────────────────────────────────

ALTER TABLE public.users
    ADD COLUMN IF NOT EXISTS display_name character varying(150);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'chk_users_display_name'
    ) THEN
        ALTER TABLE public.users
            ADD CONSTRAINT chk_users_display_name
            CHECK (display_name IS NULL OR length(trim(both from display_name)) > 0);
    END IF;
END $$;

COMMENT ON COLUMN public.users.display_name IS
    'Optional name to be shown by. NULL means "use the first and last name". Never used on a payroll document, which carries the employee record''s legal name.';

-- ── 2. A pending change of sign-in address ──────────────────────────────────

CREATE TABLE IF NOT EXISTS public.email_change_requests (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      bigint                   NOT NULL REFERENCES public.users(id),
    new_email    character varying(255)   NOT NULL,
    -- Hashed with the same encoder as a password. Never the code itself.
    code_hash    character varying(255)   NOT NULL,
    attempts     integer                  NOT NULL DEFAULT 0,
    requested_at timestamp with time zone NOT NULL DEFAULT now(),
    expires_at   timestamp with time zone NOT NULL,
    confirmed_at timestamp with time zone,
    cancelled_at timestamp with time zone,
    CONSTRAINT chk_email_change_requests_new_email
        CHECK (length(trim(both from new_email)) > 2
               AND position('@' in new_email) > 1),
    CONSTRAINT chk_email_change_requests_attempts
        CHECK (attempts >= 0),
    CONSTRAINT chk_email_change_requests_expiry
        CHECK (expires_at > requested_at),
    -- A request cannot be both confirmed and cancelled. Two ways to end, one end.
    CONSTRAINT chk_email_change_requests_one_ending
        CHECK (confirmed_at IS NULL OR cancelled_at IS NULL)
);

/*
 * ONE LIVE REQUEST PER PERSON.
 *
 * Not a tidiness rule: two live requests means two codes in two mailboxes, and
 * whichever is typed first wins — so which address the account ends up at would
 * depend on the order somebody reads their mail. Starting a new change cancels
 * the one before it, and this index is what makes that the only reachable state.
 */
CREATE UNIQUE INDEX IF NOT EXISTS uq_email_change_requests_live
    ON public.email_change_requests (user_id)
    WHERE confirmed_at IS NULL AND cancelled_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_email_change_requests_user
    ON public.email_change_requests (user_id, requested_at DESC);

COMMENT ON TABLE public.email_change_requests IS
    'A change of sign-in address, held until the person proves they can read the new mailbox. The old address stays active throughout.';
