-- =============================================================================
-- A leave somebody enters for a whole period
-- =============================================================================
-- WHAT CHANGES
--   1. work_code_categories gains one column:
--        sick_leave_kind  varchar(20)  — STANDARD | INJURY | EXTENDED, only
--                         meaningful on rows whose type = 'SICK_LEAVE'
--   2. A new table employee_leave_periods: the RECORD OF INTENT behind a
--      stretch of sick leave or vacation entered as one period rather than
--      shift by shift.
--
-- WHY A KIND AND NOT THE CATEGORY CODE
--   The thirty-day rule ("after 30 continuous calendar days of ordinary sick
--   leave, the leave continues at the fund's expense") needs to know WHICH
--   sick-leave category is the ordinary one and which is the over-thirty one.
--   The codes B / BP / B30 are data, not law — an admin can rename or add
--   categories — so the rule keys on a declared kind instead of pattern-matching
--   names or hard-coding codes:
--
--     STANDARD  — ordinary sick leave; days of it feed the 30-day count
--     INJURY    — injury at work; a DIFFERENT kind, so it BREAKS that count
--     EXTENDED  — sick leave past 30 days; what the count escalates INTO
--
-- WHY A PERIOD TABLE WHEN THE SHIFTS ALREADY EXIST
--   The shifts are the material truth — they are what payroll reads. But a
--   period entered as "on sick leave 12.01.–20.02." also has to keep meaning
--   something for months whose kartoni DO NOT EXIST YET: when February's
--   kartoni are created, the creation looks here to find who is still away and
--   materialises those days. A shift row cannot carry that forward-looking
--   fact, and deriving it from January's last shift would be a guess.
--   The table is universal — the category FK points at any absence or
--   sick-leave category, so vacations (GO) and future leave types use the same
--   row shape.
--
-- WHAT HAPPENS TO EXISTING DATA
--   Categories: the three live sick-leave rows are stamped with their kinds by
--   category_no (B → STANDARD, BP → INJURY, B30 → EXTENDED), guarded by
--   type = 'SICK_LEAVE' so a same-coded WORK category could never be touched.
--   Rows the stamp does not recognise stay NULL, which the application treats
--   as "takes no part in the thirty-day rule". Nothing else changes; the new
--   table starts empty.
--
--   · Rollback: DROP TABLE employee_leave_periods;
--       ALTER TABLE work_code_categories DROP COLUMN sick_leave_kind;
-- =============================================================================

ALTER TABLE work_code_categories
    ADD COLUMN sick_leave_kind varchar(20)
        CONSTRAINT chk_work_code_categories_sick_leave_kind
            CHECK (sick_leave_kind IN ('STANDARD', 'INJURY', 'EXTENDED'));

COMMENT ON COLUMN work_code_categories.sick_leave_kind IS
    'STANDARD | INJURY | EXTENDED — the role this SICK_LEAVE category plays in the 30-day rule; NULL = not part of it.';

UPDATE work_code_categories SET sick_leave_kind = 'STANDARD'
 WHERE category_no = 'B'   AND type = 'SICK_LEAVE' AND sick_leave_kind IS NULL;
UPDATE work_code_categories SET sick_leave_kind = 'INJURY'
 WHERE category_no = 'BP'  AND type = 'SICK_LEAVE' AND sick_leave_kind IS NULL;
UPDATE work_code_categories SET sick_leave_kind = 'EXTENDED'
 WHERE category_no = 'B30' AND type = 'SICK_LEAVE' AND sick_leave_kind IS NULL;

CREATE TABLE employee_leave_periods (
    id                    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id           bigint NOT NULL REFERENCES employees (id),
    work_code_category_id bigint NOT NULL REFERENCES work_code_categories (id),
    date_from             date   NOT NULL,
    date_to               date   NOT NULL,
    note                  varchar(255),
    created_by            bigint REFERENCES users (id),
    created_at            timestamptz NOT NULL DEFAULT now(),
    updated_at            timestamptz,
    archived_at           timestamptz,
    archived_by           bigint REFERENCES users (id),
    CONSTRAINT chk_employee_leave_periods_range CHECK (date_to >= date_from)
);

COMMENT ON TABLE employee_leave_periods IS
    'A leave (sick leave, vacation, ...) entered as one od–do period. The record of intent; the created work_shifts are the material truth payroll reads.';

CREATE INDEX idx_employee_leave_periods_employee_range
    ON employee_leave_periods (employee_id, date_from, date_to)
    WHERE archived_at IS NULL;
