-- =============================================================================
-- A shift can start when the worker does
-- =============================================================================
-- WHAT CHANGES
--   One new table, employee_shift_time_periods: WHEN a given shift runs — for
--   one employee, or by default for everybody. Shift I is 06–14 for the
--   factory, but a worker who standardly comes at 08 works I from 08–16; that
--   fact lives here, dated, so it can change over time and still be read back.
--
-- HOW A ROW IS READ
--   employee_id set   → this employee's own hours for that shift.
--   employee_id NULL  → the shift's DEFAULT hours, versioned. The default rows
--                       exist so "what should this person have worked on that
--                       date" stays answerable even after the default moves —
--                       shifts.start_time/end_time keep only the CURRENT value,
--                       as the mirror every picker already reads.
--   Resolution on a date: the employee's row covering the date wins; otherwise
--   the default row covering it; otherwise the shifts row itself (older than
--   any period, or data inserted around this table).
--
-- WHY PERIODS AND NOT A COLUMN ON employees
--   The same employee can have custom hours on shift I and default hours on
--   shift II, and either can change from a date. This is exactly the dated
--   per-employee shape employee_work_category_periods and
--   employee_employment_periods already use, so it uses it too: valid_from
--   inclusive, valid_to inclusive and NULL while in force, archived_at for a
--   row that should never have existed.
--
-- WHAT THIS DOES NOT TOUCH
--   work_shifts rows keep carrying their own start_at/end_at — the material
--   truth payroll reads. This table only changes what SEEDS those rows (and
--   what the boundary recalculation shrinks back to). Nothing historical is
--   rewritten by this migration; the seed below only restates today's shift
--   times as open-ended default periods.
--
--   · Rollback: DROP TABLE employee_shift_time_periods;
--       DELETE FROM audit_tables WHERE table_name = 'employee_shift_time_periods';
-- =============================================================================

CREATE TABLE employee_shift_time_periods (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- NULL = the shift's default hours, a real employee = that person's own.
    employee_id bigint REFERENCES employees (id),
    shift_id    bigint NOT NULL REFERENCES shifts (id),
    start_time  time   NOT NULL,
    end_time    time   NOT NULL,
    valid_from  date   NOT NULL,
    valid_to    date,
    note        varchar(255),
    created_by  bigint REFERENCES users (id),
    created_at  timestamptz NOT NULL DEFAULT now(),
    updated_at  timestamptz,
    archived_at timestamptz,
    archived_by bigint REFERENCES users (id),
    -- end < start is legal (an overnight shift, as in shifts itself); equal is not.
    CONSTRAINT chk_estp_times_differ CHECK (start_time <> end_time),
    CONSTRAINT chk_estp_range CHECK (valid_to IS NULL OR valid_to >= valid_from)
);

COMMENT ON TABLE employee_shift_time_periods IS
    'When a shift runs, dated: employee_id set = that person''s own hours for the shift, employee_id NULL = the shift''s default hours (versioned). Seeds work_shifts.start_at/end_at; never rewrites them.';
COMMENT ON COLUMN employee_shift_time_periods.employee_id IS
    'NULL = the default row for the shift; set = this employee''s override of it.';
COMMENT ON COLUMN employee_shift_time_periods.valid_to IS
    'Inclusive, like every other period here. NULL = still in force.';

-- One period in force at a time, per (shift, employee-or-default). The same
-- guard department_head_periods uses; btree_gist is in the baseline.
ALTER TABLE employee_shift_time_periods
    ADD CONSTRAINT ex_estp_no_overlap EXCLUDE USING gist (
        shift_id WITH =,
        COALESCE(employee_id, ('-1'::integer)::bigint) WITH =,
        daterange(valid_from,
                  CASE WHEN valid_to IS NULL THEN NULL::date ELSE (valid_to + 1) END)
            WITH &&
    ) WHERE (archived_at IS NULL);

-- The resolver's lookup: a shift + a date, employee row first, default second.
CREATE INDEX idx_estp_lookup
    ON employee_shift_time_periods (shift_id, employee_id, valid_from)
    WHERE archived_at IS NULL;
CREATE INDEX idx_estp_employee
    ON employee_shift_time_periods (employee_id)
    WHERE archived_at IS NULL;

CREATE TRIGGER trg_03_estp_updated_at
    BEFORE UPDATE ON employee_shift_time_periods
    FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- ── Auditing ─────────────────────────────────────────────────────────────────

INSERT INTO public.audit_tables (table_name)
SELECT 'employee_shift_time_periods'
WHERE NOT EXISTS (
    SELECT 1 FROM public.audit_tables WHERE table_name = 'employee_shift_time_periods'
);

DROP TRIGGER IF EXISTS trg_audit_logs_employee_shift_time_periods
    ON public.employee_shift_time_periods;
CREATE TRIGGER trg_audit_logs_employee_shift_time_periods
    AFTER INSERT OR DELETE OR UPDATE ON public.employee_shift_time_periods
    FOR EACH ROW EXECUTE FUNCTION public.audit_trigger_fn();

-- ── Seed: today's defaults, restated as open-ended periods ───────────────────
-- valid_from is deliberately far in the past: the default period must cover
-- every date the app can ever be asked about, or the resolver would fall back
-- to the mutable shifts row for old kartone and history would drift with it.

INSERT INTO employee_shift_time_periods (shift_id, start_time, end_time, valid_from, note)
SELECT s.id, s.start_time, s.end_time, DATE '1970-01-01',
       'Podrazumevano vreme smene, preneto pri uvođenju istorije smena.'
FROM shifts s
WHERE NOT EXISTS (
    SELECT 1 FROM employee_shift_time_periods p
    WHERE p.shift_id = s.id AND p.employee_id IS NULL
);
