-- =============================================================================
-- A deadline warns before it expires — and warns each moment only once
-- =============================================================================
-- WHAT CHANGES
--   · order_reminders (new): the record of every reminder the morning job has
--     already sent — one row per (order, subject, deadline date, threshold).
--   · production_orders: completion_notified_at — when the "all line items
--     are done" mail went out, null until it does.
--
-- WHY A LOG TABLE AND NOT A FLAG
--   The 09:00 job asks, for every open order, "is any deadline 7, 3 or 0 days
--   away, and have we said so YET?" — and 'yet' is per deadline, per date,
--   per threshold: a successive delivery, a line item's partial quantity and
--   the sample order's single rok each warn on their own schedule, and a
--   deadline that is MOVED must warn again for its new date. A flag on the
--   order cannot carry that; a row per sent warning carries exactly that and
--   nothing else. The unique index is what makes the job idempotent — a rerun
--   or a restart inserts nothing new and therefore sends nothing new.
--
--   subject_key names WHICH deadline warned ('ORDER' — the order's own rok;
--   'DEADLINE' — a successive delivery line; 'ITEM:<product id>' — a line
--   item's partial quantity), so the same calendar date on two subjects still
--   warns twice — they are two different obligations.
--
-- WHY completion_notified_at IS ON THE ORDER
--   "Every line item is done" is announced once in the order's life, and the
--   order itself is the only row with that lifetime. Progress is computed at
--   read time (V33) and can even move backwards when scope changes; the
--   timestamp records that the announcement HAPPENED, which no recomputation
--   can un-happen.
--
-- WHAT HAPPENS TO EXISTING DATA
--   Nothing rewritten. Existing orders get null completion_notified_at — for
--   an already-delivered order the job never looks, and for an open one at
--   100% the next morning announces it, which is the honest reading: nobody
--   was ever told.
--
--   Guarded (IF EXISTS / IF NOT EXISTS); replaying is safe.
--
-- Rollback:
--   DROP TABLE public.order_reminders;
--   ALTER TABLE public.production_orders DROP COLUMN completion_notified_at;
-- =============================================================================

CREATE TABLE IF NOT EXISTS public.order_reminders (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_type      character varying(20) NOT NULL,
    order_id        bigint NOT NULL,
    subject_key     character varying(120) NOT NULL,
    deadline_date   date NOT NULL,
    threshold_days  smallint NOT NULL,
    sent_at         timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT chk_order_reminders_order_type
        CHECK (order_type IN ('PRODUCTION', 'SAMPLE')),
    CONSTRAINT chk_order_reminders_threshold
        CHECK (threshold_days IN (0, 3, 7))
);

-- The idempotency guarantee itself: one warning per (order, subject, date,
-- threshold), enforced where a concurrent or replayed run cannot argue with it.
CREATE UNIQUE INDEX IF NOT EXISTS uq_order_reminders_once
    ON public.order_reminders (order_type, order_id, subject_key, deadline_date, threshold_days);

-- What the job scans every morning.
CREATE INDEX IF NOT EXISTS idx_order_reminders_order
    ON public.order_reminders (order_type, order_id);

ALTER TABLE public.production_orders
    ADD COLUMN IF NOT EXISTS completion_notified_at timestamp with time zone;

COMMENT ON TABLE public.order_reminders IS
    'Every deadline reminder the morning job has sent — the unique index is what keeps a rerun silent.';
COMMENT ON COLUMN public.order_reminders.subject_key IS
    'Which deadline warned: ORDER (the order''s own rok), DEADLINE (a successive delivery line), ITEM:<product id> (a line item''s partial quantity).';
COMMENT ON COLUMN public.production_orders.completion_notified_at IS
    'When the "all line items done" notice went out; null until it does. Written once by the morning job.';
