-- =============================================================================
-- An order can carry public notes anyone signed in may write
-- =============================================================================
-- WHAT CHANGES
--   One new table, order_notes. A note is a short thing somebody on the floor,
--   in the office or in the shop leaves ON an order for everyone else who opens
--   it — "čeka boju", "kupac pomerio rok", "materijal stigao". It is not the
--   order's own single `note` field (that is the commercial's, one per order and
--   edited through the order form); this is a running wall many hands write on.
--
-- WHY ONE TABLE FOR BOTH ORDER KINDS
--   The two kinds of order — production_orders and sample_orders — carry the
--   exact same wall, written by the same people under the same rules. A table
--   apiece would be two of everything (entity, repository, service, controller)
--   for one behaviour, and the two would drift. Instead one table points at
--   EITHER parent through two nullable foreign keys, and a CHECK makes exactly
--   one of them present on every row. The foreign keys are real — a note cannot
--   outlive an order that never existed — and ON DELETE CASCADE means a note
--   never survives its order as an orphan.
--
--   Both keys are indexed only where they are set (partial indexes), so the feed
--   for one order — "this order's notes, newest first" — is one index range scan
--   whichever kind of order it is.
--
-- WHY THE BODY IS jsonb AND ALSO text
--   The editor on the screen (BlockNote) speaks a document of blocks, not a
--   string: headings, lists, links. body_json holds that document verbatim, so
--   what was written is what is read back. body_text is the same note flattened
--   to plain text ON WRITE by the application, and it is what search, sort and
--   the one-line preview read — a jsonb document is the wrong thing to run
--   `lower(...) like '%rok%'` over. The two are always written together; the
--   flattening lives in one place in the backend so they cannot disagree.
--
-- WHO MAY WRITE, EDIT, DELETE
--   Enforced in the service, NOT here: everyone signed in may WRITE (this is the
--   whole point — the wall is the company's), the AUTHOR may edit and delete
--   their own, and an administrator/director/developer may moderate any. The
--   table records author_user_id so the service can answer "is this yours", and
--   RESTRICT on that key keeps authorship readable — a note must always be able
--   to say who wrote it.
--
-- WHY A SOFT DELETE
--   Deleting a note archives it (is_active = false, archived_at set) rather than
--   removing the row, the same shape every other record here uses, so a note the
--   floor acted on is never silently gone. The CHECK ties the two together: an
--   archived note is always inactive.
--
-- MIGRATION IMPACT
--   · Purely additive. One new table; nothing existing is read, rewritten or
--     dropped, and no payroll or norm figure can move.
--   · Guarded (IF NOT EXISTS) and safe to replay.
--   · Rollback is DROP TABLE public.order_notes.
-- =============================================================================

CREATE TABLE IF NOT EXISTS public.order_notes (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Exactly one of these is set; the CHECK below enforces it.
    production_order_id bigint,
    sample_order_id     bigint,

    author_user_id      bigint      NOT NULL,

    body_json           jsonb       NOT NULL,
    body_text           text        NOT NULL DEFAULT '',

    is_active           boolean     NOT NULL DEFAULT true,

    created_at          timestamptz NOT NULL DEFAULT now(),
    updated_at          timestamptz,
    archived_at         timestamptz,

    CONSTRAINT fk_order_notes_production_order
        FOREIGN KEY (production_order_id) REFERENCES public.production_orders (id) ON DELETE CASCADE,
    CONSTRAINT fk_order_notes_sample_order
        FOREIGN KEY (sample_order_id) REFERENCES public.sample_orders (id) ON DELETE CASCADE,
    CONSTRAINT fk_order_notes_author
        FOREIGN KEY (author_user_id) REFERENCES public.users (id) ON DELETE RESTRICT,

    -- The note belongs to one order, and to exactly one KIND of order.
    CONSTRAINT chk_order_notes_one_parent
        CHECK (num_nonnulls(production_order_id, sample_order_id) = 1),

    -- An archived note is always inactive — the same invariant the line-item
    -- notes carry.
    CONSTRAINT chk_order_notes_archived_implies_inactive
        CHECK (archived_at IS NULL OR is_active = false)
);

-- The feed reads "this order's notes, newest first" — one range scan per order,
-- and only over rows that actually hang off that kind of order.
CREATE INDEX IF NOT EXISTS idx_order_notes_production_order
    ON public.order_notes USING btree (production_order_id, created_at DESC)
    WHERE production_order_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_order_notes_sample_order
    ON public.order_notes USING btree (sample_order_id, created_at DESC)
    WHERE sample_order_id IS NOT NULL;

-- Filtering a wall down to one colleague's notes.
CREATE INDEX IF NOT EXISTS idx_order_notes_author
    ON public.order_notes USING btree (author_user_id);

-- updated_at is stamped by the shared touch function (see V13), exactly as every
-- other table with an updated_at uses it.
DROP TRIGGER IF EXISTS trg_03_order_notes_updated_at ON public.order_notes;
CREATE TRIGGER trg_03_order_notes_updated_at
    BEFORE UPDATE ON public.order_notes
    FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

COMMENT ON TABLE public.order_notes IS
    'Public notes many people leave on an order (production or sample). Distinct '
    'from production_orders.note / sample_orders.note, which are the order''s own '
    'single commercial note. body_json is the BlockNote document; body_text is it '
    'flattened for search/sort/preview. Exactly one parent FK is set per row.';
