-- =============================================================================
-- A performance mark carries a price
-- =============================================================================
-- WHAT CHANGES
--   One new table, performance_marks: the šifarnik of OCENE — a mark (4.5, 3,
--   1) and what that mark does to the HOURLY RATE of whoever receives it.
--   Nothing here assigns a mark to anybody; the monthly per-employee
--   assignment (inside the payroll flow) comes later and will reference this
--   table. Until then the šifarnik only exists and is editable.
--
-- HOW A ROW IS READ
--   mark 3, amount -40, amount_unit RSD_PER_HOUR, valid 2026-10-01 → NULL
--   means: from 1 October, an employee graded 3 has 40 dinara taken off each
--   hour's rate. amount_unit PERCENT reads the same amount as a percentage of
--   the rate instead: -40 → the rate × 0.60. The sign is part of the value —
--   negative is a deduction, positive a bonus; both are legal.
--
-- WHY PERIODS AND NOT A MUTABLE VALUE
--   What a mark was worth WHEN A MONTH WAS CALCULATED must stay answerable
--   after the value moves, or old obračuni stop being explainable. So the
--   value is dated the way every other dated value here is dated
--   (employee_shift_time_periods, employee_work_category_periods): valid_from
--   inclusive, valid_to inclusive and NULL while in force, archived_at for a
--   row that should never have existed. Editing a mark's value = closing the
--   period and opening a new one, in the service, never an UPDATE of amount
--   on a row somebody's payroll already read.
--
-- WHAT THIS DELIBERATELY LEAVES OPEN
--   Whether a deduction may drag an hourly rate below zero is a payroll rule,
--   decided where the mark is APPLIED, not here — the šifarnik records the
--   decision "ocena 3 = -40 RSD/h" and nothing else. Likewise the table does
--   not know a fixed grading scale: mark is numeric, and which marks exist is
--   whatever rows the admin creates.
--
--   · Rollback: DROP TABLE performance_marks;
--       DELETE FROM audit_tables WHERE table_name = 'performance_marks';
-- =============================================================================

CREATE TABLE performance_marks (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- The mark itself, e.g. 4.5. Decimal because a mark need not be whole.
    mark        numeric(5,2)  NOT NULL,
    -- What the mark does to the hourly rate. The sign is part of the value:
    -- negative = deduction, positive = bonus.
    amount      numeric(12,2) NOT NULL,
    -- How amount is read against the hourly rate. Closed set on purpose;
    -- widening it later is one ALTER of this CHECK.
    amount_unit varchar(16)   NOT NULL
        CONSTRAINT chk_pm_amount_unit CHECK (amount_unit IN ('PERCENT', 'RSD_PER_HOUR')),
    valid_from  date NOT NULL,
    -- Inclusive, like every other period here. NULL = still in force.
    valid_to    date,
    note        varchar(255),
    created_by  bigint REFERENCES users (id),
    created_at  timestamptz NOT NULL DEFAULT now(),
    updated_at  timestamptz,
    archived_at timestamptz,
    archived_by bigint REFERENCES users (id),
    CONSTRAINT chk_pm_range CHECK (valid_to IS NULL OR valid_to >= valid_from)
);

COMMENT ON TABLE performance_marks IS
    'Šifarnik ocena učinka: šta ocena (mark) radi ceni radnog sata, datirano. Verzija se menja zatvaranjem perioda i otvaranjem novog, nikad prepisivanjem iznosa.';
COMMENT ON COLUMN performance_marks.amount_unit IS
    'PERCENT = amount je procenat satnice; RSD_PER_HOUR = amount je dinara po satu.';
COMMENT ON COLUMN performance_marks.valid_to IS
    'Inclusive, like every other period here. NULL = still in force.';

-- One value in force at a time per mark. The same gist guard
-- employee_shift_time_periods uses; btree_gist is in the baseline.
ALTER TABLE performance_marks
    ADD CONSTRAINT ex_pm_no_overlap EXCLUDE USING gist (
        mark WITH =,
        daterange(valid_from,
                  CASE WHEN valid_to IS NULL THEN NULL::date ELSE (valid_to + 1) END)
            WITH &&
    ) WHERE (archived_at IS NULL);

-- The lookup: which value of mark X is in force on date D.
CREATE INDEX idx_pm_lookup
    ON performance_marks (mark, valid_from)
    WHERE archived_at IS NULL;

CREATE TRIGGER trg_03_pm_updated_at
    BEFORE UPDATE ON performance_marks
    FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- ── Auditing ─────────────────────────────────────────────────────────────────

INSERT INTO public.audit_tables (table_name)
SELECT 'performance_marks'
WHERE NOT EXISTS (
    SELECT 1 FROM public.audit_tables WHERE table_name = 'performance_marks'
);

DROP TRIGGER IF EXISTS trg_audit_logs_performance_marks
    ON public.performance_marks;
CREATE TRIGGER trg_audit_logs_performance_marks
    AFTER INSERT OR DELETE OR UPDATE ON public.performance_marks
    FOR EACH ROW EXECUTE FUNCTION public.audit_trigger_fn();
