-- =============================================================================
-- The supervisor's board reads yesterday's answer, it does not compute one
-- =============================================================================
-- WHAT CHANGES
--   1. dashboard_insights — one row per (insight, day): the finished answer to
--      one analytical question, stored as JSON. A scheduled job writes it once
--      a day; the control board only reads the newest row per key.
--
--   2. app_settings key `sick_leave_work_code_category_nos` — which work codes
--      MEAN sick leave. Nothing in the schema said so: work_code_categories.type
--      is free text, so "who is on sick leave" was not a question the data could
--      answer. It is a factory decision, so it is a setting somebody edits in
--      Parametri, not a constant in the code.
--
-- WHY A SNAPSHOT AT ALL
--   The questions are the expensive kind — average performance per operation
--   over a month, spread between employees on one operation, shifts with no
--   entries. Recomputing them every time somebody opens their home screen would
--   put a minute of aggregation behind a page that is glanced at. They also do
--   not change minute to minute: an operation whose norm is wrong today was
--   wrong yesterday.
--
-- WHY JSONB AND NOT A COLUMN PER FIGURE
--   Each insight has its own row shape, and the list of insights is expected to
--   grow. A typed table per insight would mean a migration for every new card.
--   The payload is written by one service and read by one service, both of which
--   already own the shape — the database is storage here, not the contract.
--
--   Keeping a row PER DAY rather than overwriting one row also gives the board
--   its trend for free: today's count against yesterday's is two rows, not a
--   second history table.
--
-- MIGRATION IMPACT
--   · Additive only. No existing table, column or constraint is touched.
--   · Nothing reads the new table until the job has run once; every card is
--     written to say "još nije izračunato" rather than to show a zero.
--   · The setting is seeded EMPTY on purpose. An empty value means "nobody has
--     said which codes are sick leave", and the card says exactly that instead
--     of silently reporting that nobody is absent.
--   · Every step is guarded, so replaying the migration is safe.
--   · Rollback: DROP TABLE dashboard_insights, and delete the settings row.
-- =============================================================================

CREATE TABLE IF NOT EXISTS dashboard_insights (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    insight_key  character varying(60)    NOT NULL,
    computed_for date                     NOT NULL,
    computed_at  timestamp with time zone NOT NULL DEFAULT now(),
    window_days  integer,
    payload      jsonb                    NOT NULL,
    CONSTRAINT uq_dashboard_insights_key_day UNIQUE (insight_key, computed_for),
    CONSTRAINT chk_dashboard_insights_key_not_empty
        CHECK (length(trim(both from insight_key)) > 0),
    CONSTRAINT chk_dashboard_insights_window_days
        CHECK (window_days IS NULL OR window_days > 0)
);

COMMENT ON TABLE dashboard_insights IS
    'One finished analytical answer per (insight_key, computed_for). Written by the daily job, read by the control boards.';

-- The board asks for "the newest row for these keys", which is what this serves.
CREATE INDEX IF NOT EXISTS idx_dashboard_insights_key_day
    ON dashboard_insights (insight_key, computed_for DESC);

-- Which work codes mean sick leave. Comma-separated category_no values, e.g. "40,41".
-- category_no rather than id: it is what the factory calls the code, and it stays
-- the same across the validity versions of one category.
INSERT INTO app_settings (
    setting_key, value_type, setting_value_text, display_text, description,
    is_active, affects_payroll, valid_from
)
SELECT
    'sick_leave_work_code_category_nos',
    'text',
    '',
    'Šifre rada koje znače bolovanje',
    'Unesite šifre odvojene zarezom (npr. 40,41). Koristi se samo za prikaz odsutnih na kontrolnoj tabli — ne utiče na obračun.',
    true,
    false,
    now()
WHERE NOT EXISTS (
    SELECT 1 FROM app_settings WHERE setting_key = 'sick_leave_work_code_category_nos'
);
